{% set name = "mo-dots" %}
{% set version = "5.22.21182" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-dots-{{ version }}.tar.gz
  sha256: d25c9505c7bfad2f09175afedd026438b7b3128f5070d4f301618e86202037f1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - mo-future 3.147.20327
    - mo-imports 3.149.20327
    - python >=2.7

test:
  imports:
    - mo_dots
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/klahnakoski/mo-dots
  summary: More Dots! Dot-access to Python dicts like Javascript
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
