{% set name = "mo-dots" %}
{% set version = "9.169.22121" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-dots-{{ version }}.tar.gz
  sha256: 90ce0d1bd4ee60eb0b1b79a80ddedecf14d36f1ef74051b66af90e37685022cd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - mo-future ==6.2.21303
    - mo-imports ==7.169.22121
    - python >=2.7

test:
  imports:
    - mo_dots
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/klahnakoski/mo-dots
  summary: More Dots! Dot-access to Python dicts like Javascript
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
