{% set name = "mo-dots" %}
{% set version = "9.128.22026" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-dots-{{ version }}.tar.gz
  sha256: 17c1291e23c618fa828687a9615ba9c87f02e3796f95f263e4b38be3e1fbd222

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - mo-future 6.2.21303
    - mo-imports 7.109.22021
    - python >=2.7

test:
  imports:
    - mo_dots
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/klahnakoski/mo-dots
  summary: More Dots! Dot-access to Python dicts like Javascript
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
