{% set name = "mo-dots" %}
{% set version = "9.300.22349" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-dots-{{ version }}.tar.gz
  sha256: fcadf2c647140f4e0e47a07324220cfd1e55bba11546f11e6baff0f4cecdea9b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - mo-future ==7.298.22349
    - mo-imports ==7.298.22349
    - python >=2.7

test:
  imports:
    - mo_dots
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/klahnakoski/mo-dots
  summary: More Dots! Dot-access to Python dicts like Javascript
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
